version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@postgres:5432/basic_api_dev
      - SECRET_KEY_BASE=BKqUIk2R1F0Cz0akgxMRFZ32Q4Ej+W//knY/HcqPuWSxijVxcZ8z/H8B2DPI0HcX
      - MIX_ENV=prod
    depends_on:
      - postgres
    networks:
      - basic-api-network
    command: >
      sh -c "
        mix deps.get &&
        mix deps.compile &&
        mix ecto.setup
        mix phx.server
        ls --ignore=deps --ignore=_build --ignore=priv --ignore=assets | entr -r mix phx.server'
      "
    volumes:
     - .:/app

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basic_api_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - basic-api-network

volumes:
  postgres-data:

networks:
  basic-api-network:
    driver: bridge